---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1609520/public_html/
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R test $DEPLOYPATH
    - /bin/cp -R writable $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp builds $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/cp env $DEPLOYPATH
    - /bin/cp LICENSE $DEPLOYPATH
    - /bin/cp phpunit.xml.dist $DEPLOYPATH
    - /bin/cp preload.php $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
    - /bin/cp spark $DEPLOYPATH
