<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use CodeIgniter\I18n\Time;

class Users extends Seeder
{
    public function run()
    {
        // $data = [
        //     [
        //         'username' => 'driverwotle',
        //         'password' => 'driver',
        //         'nama' => 'driver wotle',
        //         'role' => 'driver',
        //         'foto' => 'driver1.jpg',
        //         'referal' => 'DRWOTL',
        //         'tautan_referal' => '',
        //         'status' => 'aktif',
        //         'point' => '5000',
        //         'ktp' => 'ktpdriver1.jpg',
        //         'sim' => 'simdriver1.jpg',
        //         'plat_nomor' => 'E74289',
        //         'tipe_kendaraan' => 'alphard x783',
        //         'created_at' => Time::now(),
        //         'updated_at' => Time::now(),
        //     ],
        //     [
        //         'username' => 'driverwotle2',
        //         'password' => 'driver2',
        //         'nama' => 'driver wotle 2',
        //         'role' => 'driver',
        //         'foto' => 'driver2.jpg',
        //         'referal' => 'DRWOTL2',
        //         'tautan_referal' => '',
        //         'status' => 'aktif',
        //         'point' => '10000',
        //         'ktp' => 'ktpdriver2.jpg',
        //         'sim' => 'simdriver2.jpg',
        //         'plat_nomor' => 'E74289',
        //         'tipe_kendaraan' => 'alphard x783',
        //         'created_at' => Time::now(),
        //         'updated_at' => Time::now(),
        //     ],
        //     [
        //         'username' => 'admin',
        //         'password' => 'admin',
        //         'nama' => 'Admin wotle',
        //         'role' => 'admin',
        //         'foto' => 'admin.jpg',
        //         'referal' => 'ADM51',
        //         'tautan_referal' => '',
        //         'status' => 'aktif',
        //         'point' => '10000',
        //         'ktp' => '',
        //         'sim' => '',
        //         'plat_nomor' => '',
        //         'tipe_kendaraan' => '',
        //         'created_at' => Time::now(),
        //         'updated_at' => Time::now(),
        //     ],
        // ];
        $data = [
                [  
                'nama' => 'Bayu Prasetyo',
                'email' => 'bayu@gmail.com',
                'password' => '$2y$10$zF9LxtALcmpOwJNPwvh.h.GAYPVn7YxTISIq8I4aUMgbW/1qE8HJm',
                'no_hp' => '083824283621',
                'foto' => 'https://firebasestorage.googleapis.com/v0/b/wotle-2ee57.appspot.com/o/profileUser%2F8812cff8-dd0b-44ae-a412-810721cd3cfb?alt=media&amp;token=8dcb0398-daba-4174-bbb1-4b80f799b2a3',    
                'ttl' => '30-08-2000',
                'alamat' => 'Kuningan',
                'no_darurat' => '',
                'status' => 'aktif',
                'role' => 'customer',
                ],
              
                [  
                'nama' => 'Apip',
                'email' => 'apip@gmail.com',
                'password' => '$2y$10$3B7r51iQgkfx4LhmwDkwu.Wu9S.r4vpQ1VI.iN95jr2SbluIxwYCG',
                'no_hp' => '083824587800',
                'foto' => 'https://lh3.googleusercontent.com/a/AItbvmnBW0wo8XpPHRkPSooeub-cxZI-nEylw06HY50s=s96-c',    
                'ttl' => '02-02-1982',
                'alamat' => 'Cibinuang',
                'no_darurat' => 'null',
                'status' => 'aktif',
                'role' => 'customer',
                ],
              
                [  
                'nama' => 'What your Name',
                'email' => 'wyuname@gmail.com',
                'password' => '',
                'no_hp' => '+15555215554',
                'foto' => 'https://lh3.googleusercontent.com/a/AItbvmnBW0wo8XpPHRkPSooeub-cxZI-nEylw06HY50s=s96-c',    
                'ttl' => 'null',
                'alamat' => 'null',
                'no_darurat' => 'null',
                'status' => 'aktif',
                'role' => 'customer',
                ],
              
                [  
                'nama' => 'Bayu Prasetyo',
                'email' => '20190810011@uniku.ac.id',
                'password' => '',
                'no_hp' => '+6283824587800',
                'foto' => 'https://lh3.googleusercontent.com/a/AItbvmmSvAxKynKxhm8MUMRkVlsSUks58qJU44352KnH=s96-c',    
                'ttl' => 'null',
                'alamat' => 'null',
                'no_darurat' => 'null',
                'status' => 'aktif',
                'role' => 'customer',
                ],
              
                [  
                'nama' => 'Bayu Channel',
                'email' => 'jimmyhopkins0077@gmail.com',
                'password' => '$2y$10$dyV5y.ymGuQSK650xcLnAO8iw0VXyJBPsdPN/BzH5JJIictHu2HuG',
                'no_hp' => '+6287824587800',
                'foto' => 'profile.png',    
                'ttl' => 'null',
                'alamat' => 'null',
                'no_darurat' => 'null',
                'status' => 'aktif',
                'role' => 'customer',
                ],
              
                [  
                'nama' => 'Hani Novitasari',
                'email' => 'onlinelingga6@gmail.com',
                'password' => '',
                'no_hp' => '',
                'foto' => 'https://lh3.googleusercontent.com/a/ALm5wu0VTr1_VmOTgtRYZFAjgKkPzBMn8nks6qSQqhW4=s96-c',    
                'ttl' => 'null',
                'alamat' => 'null',
                'no_darurat' => 'null',
                'status' => 'aktif',
                'role' => 'customer',
                ],
              
                [  
                'nama' => 'bayu praze',
                'email' => 'bayuprasetyo.bp11@gmail.com',
                'password' => '$2y$10$tP/gKqxJSiy23IOyanyz3.I8E39wRiWgMKlciakVFNQjSCAlj82h2',
                'no_hp' => '+6289537352960',
                'foto' => 'https://firebasestorage.googleapis.com/v0/b/wotle-2ee57.appspot.com/o/profileUser%2F42ad269a-3dbd-4fc7-bd71-b53f8788e6d1?alt=media&amp;token=628a0606-6ec6-42aa-ab63-ef3682a4dc23',    
                'ttl' => 'null',
                'alamat' => 'Desa Tambakbaya kecamatan garawangi kabupaten kuningan',
                'no_darurat' => 'null',
                'status' => 'aktif',
                'role' => 'customer',
                ],
              
                [  
                'nama' => 'sad',
                'email' => 'bayu1@gmail.com',
                'password' => '$2y$10$36Exkiqzc.pzX9nRijkWS.lolbxJs80lh2p1tt1zaEgpt0SPuPtsq',
                'no_hp' => '+6212345678912',
                'foto' => 'profile.png',    
                'ttl' => 'null',
                'alamat' => 'null',
                'no_darurat' => 'null',
                'status' => 'aktif',
                'role' => 'customer',
                ],
              
                [  
                'nama' => 'sddf',
                'email' => 'bayu2@gmail.com',
                'password' => '$2y$10$CgA7OXOSthbafE2VWtotQuez0n6bbwekw2hJtM6HZ5A2U/ECLXFmm',
                'no_hp' => 'null',
                'foto' => 'profile.png',    
                'ttl' => 'null',
                'alamat' => 'null',
                'no_darurat' => 'null',
                'status' => 'aktif',
                'role' => 'customer',
                ],
              
                [  
                'nama' => 'Esa Nurhidayah',
                'email' => 'onlinelingga4@gmail.com',
                'password' => '',
                'no_hp' => 'null',
                'foto' => 'https://lh3.googleusercontent.com/a/ALm5wu2P4KTzGpU8Xm-YorKmsR58AvEer6NuQwpXI2AZ=s96-c',    
                'ttl' => 'null',
                'alamat' => 'null',
                'no_darurat' => 'null',
                'status' => 'aktif',
                'role' => 'customer',
                ],
              
                [  
                'nama' => 'Dea Saputri',
                'email' => 'onlinelingga5@gmail.com',
                'password' => '',
                'no_hp' => 'null',
                'foto' => 'https://lh3.googleusercontent.com/a/ALm5wu0d147OFxa32qF1Cl-yFnIP3QRySvCTSmKF6U6m=s96-c',    
                'ttl' => 'null',
                'alamat' => 'null',
                'no_darurat' => 'null',
                'status' => 'aktif',
                'role' => 'customer',
                ],
              
                [  
                'nama' => 'Check In',
                'email' => 'checkin08390@gmail.com',
                'password' => '',
                'no_hp' => 'null',
                'foto' => 'https://lh3.googleusercontent.com/a/AItbvmmoMTuk3ktTEcxBQvZndSG1z3rFecMvYSTsrlxm=s96-c',    
                'ttl' => 'null',
                'alamat' => 'null',
                'no_darurat' => 'null',
                'status' => 'aktif',
                'role' => 'customer',
                ],
              
                [  
                'nama' => 'Brama Iqra Mubarak',
                'email' => 'bramaiqramubarak123@gmail.com',
                'password' => '',
                'no_hp' => 'null',
                'foto' => 'https://lh3.googleusercontent.com/a/ALm5wu0arE-A_xTwfJQJ9KyAbRbZE0PYUlCwST0JTBLz=s96-c',    
                'ttl' => 'null',
                'alamat' => 'null',
                'no_darurat' => 'null',
                'status' => 'aktif',
                'role' => 'customer',
                ],
              
                [  
                'nama' => 'jhony',
                'email' => 'jhony@gmail.com',
                'password' => '$2y$10$3B7r51iQgkfx4LhmwDkwu.Wu9S.r4vpQ1VI.iN95jr2SbluIxwYCG',
                'no_hp' => '0895373547243',
                'foto' => '',    
                'ttl' => '',
                'alamat' => '',
                'no_darurat' => '',
                'status' => 'aktif',
                'role' => 'customer',
                ],
              
                [  
                'nama' => 'ardi triyana',
                'email' => 'ardi@gmail.com',
                'password' => '$2y$10$3B7r51iQgkfx4LhmwDkwu.Wu9S.r4vpQ1VI.iN95jr2SbluIxwYCG',
                'no_hp' => '',
                'foto' => '',    
                'ttl' => '',
                'alamat' => '',
                'no_darurat' => '',
                'status' => 'aktif',
                'role' => 'customer',
                ],
              
                [  
                'nama' => 'Sendi Bayu Nugraha',
                'email' => 'sendi@gmail.com',
                'password' => '$2y$10$QaeEQEhzvHyaYbmmdsIIcO68j8TzL2V0oH4qN/S5vR04hrLt5iXXm',
                'no_hp' => '0896798347923',
                'foto' => '',    
                'ttl' => '',
                'alamat' => '',
                'no_darurat' => '',
                'status' => 'aktif',
                'role' => 'customer',
                ],
              
                [  
                'nama' => 'Raimu',
                'email' => 'raimu@gmail.com',
                'password' => '$2y$10$Na26zO4lHxEGlraRreQy6uwlCEDpymDo8mBrbWI5o6UyLm0qgyuO6',
                'no_hp' => '+6283854321780',
                'foto' => 'profile.png',    
                'ttl' => 'null',
                'alamat' => 'null',
                'no_darurat' => 'null',
                'status' => 'aktif',
                'role' => 'customer',
                ],
              
                [  
                'nama' => 'Sendi Bayu Nugraha',
                'email' => 'nugraha102210@gmail.com',
                'password' => '$2y$10$tfmOErDevnvYN4NB46TJreWhsvAuhmNHj2Pf10VUgJ2QFJCaZk3GS',
                'no_hp' => '+62895355277221',
                'foto' => 'profile.png',    
                'ttl' => 'null',
                'alamat' => 'null',
                'no_darurat' => 'null',
                'status' => 'aktif',
                'role' => 'customer',
                ],
              
                [  
                'nama' => 'adi miftahul azis',
                'email' => 'adimiftahul98@gmail.com',
                'password' => '$2y$10$XnOmlEEsm9zi.wJsKrVbHe1QCGqEAJHi3hh2Jeb5EiEwKYUiY3ypW',
                'no_hp' => '+6283823067018',
                'foto' => 'profile.png',    
                'ttl' => 'null',
                'alamat' => 'null',
                'no_darurat' => 'null',
                'role' => 'customer',
                'status' => 'aktif',
                ],
        ];
        $this->db->table('users')->insertBatch($data);
    }
}
